services:
  frontend:
    container_name: frontend_dev
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true # depricated from react-script@5.0.0
      - WATCHPACK_POLLING=true # use WATCHPACK_POLLING from react-script@5.0.0
    command: [npm, start]
    ports:
      - 53001:3000
  backend:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: [sh, build.sh]
    ports:
      - 53000:3000
